FROM fedora:34

# Metadata
LABEL author  "error23"
LABEL email   "error23.d@gmail.com"
LABEL version "1.0"
LABEL created "19/06/2021"

# Install system dependencies
#RUN dnf update
#RUN dnf upgrade
#RUN dnf install tree -y
#RUN dnf install git -y
#RUN dnf install gettext -y

